### ISSUE TITLE
Save List view or Icon view preference somewhere?

### ISSUE THREAD

**Issue by ponceta** [opengisch/qgis-document-management-system-plugin#10]
If a user likes the list view or the icon view, he should be able to have its favorite view and not being pushed to switch view every time. Ergonomic enhancement. On windows it's the last setting used.

**Comment by domi4484** [comment]
Thank you for the suggestion, there could be a "Default view" settings with three options like
- Remember last
- List view
- Icon view

**Comment by 3nids** [comment]
fixed
