### ISSUE TITLE
Slowed form opening / white screen

### ISSUE THREAD

**Issue by ponceta** [opengisch/qgis-document-management-system-plugin#19]
This is small but the form opening is slightly slowed when we include a document management system widget

You can see the white screen when the form is opened in the capture below.

![TEKSI_Document_manager_troncons](https://user-images.githubusercontent.com/8614223/128979147-50fb7346-9663-449f-a6e1-5f43b7eb8f3a.gif)

**Comment by domi4484** [comment]
Project + data needed to replicate the issue

**Comment by 3nids** [comment]
I think we should implement the same thing than here: https://github.com/opengisch/qgis-ordered-relation-editor/pull/5

**Comment by domi4484** [comment]
Widgets opening time should be much better in version 0.3.0. Please let me know if it is not the case
