### ISSUE TITLE
Drag & Drop method store the filepath in the database

### ISSUE THREAD

**Issue by jpdupuy** [opengisch/qgis-document-management-system-plugin#22]
When you add a new document, the filepath is different when registered in the database
with the select file button, the path is not stored
![image](https://user-images.githubusercontent.com/72449015/129754693-0380afc8-ef7a-4312-9278-8628957ff8a4.png)
![image](https://user-images.githubusercontent.com/72449015/129754793-f06b05bb-4b24-464d-9762-cd63891f2dde.png)

When the drag & drop is used the path is stored
![image](https://user-images.githubusercontent.com/72449015/129754859-25d437d2-4a34-434e-9892-19a7dcd11754.png)
![image](https://user-images.githubusercontent.com/72449015/129754893-905f406b-d447-4152-872d-3fb40811ae80.png)

**Comment by domi4484** [comment]
@jpdupuy thank you for the feedback!
Do you dropped the file in the document relation editor widget or directly in the document form on the attachment widget?

I just tried directly on the attachment widget and it does not take care of the default path when dropping a file.

**Comment by jpdupuy** [comment]
I used both methods (see the 2 snapshots).
drag & drop : I get the full path
attachement : I get the relative path

**Comment by domi4484** [comment]
Yes what I meant is if you drag&dropped the file into the document relation editor widget (coming from the plugin) or into the attachment widget (coming from QGIS).
It seems the bug is in QGIS itself.

**Comment by domi4484** [comment]
@jpdupuy fix submitted in the QGIS project: https://github.com/qgis/QGIS/pull/44798

**Comment by domi4484** [comment]
@jpdupuy the fix was integrated into QGIS and you should be able to test it in the nightly builds. It will also be backported to the next point release of 3.16 and 3.20.
