### ISSUE TITLE
Feature side configuration : Many files to one feature

### ISSUE THREAD

**Issue by ponceta** [opengisch/qgis-document-management-system-plugin#3]
QGIS 3.18.X / Win 10 x64

For an existing relation with a relationnal widget i have this :

![image](https://user-images.githubusercontent.com/8614223/120601593-7127f480-c44a-11eb-8083-58c70d92c3a9.png)

Try to set Feature side widget : (with qgep_od.vw_file as linked document table)

![image](https://user-images.githubusercontent.com/8614223/120601719-974d9480-c44a-11eb-8d9d-0024bc569d04.png)

I end with no error but no file displayed

![image](https://user-images.githubusercontent.com/8614223/120601848-b64c2680-c44a-11eb-8e37-cae97fe767f9.png)

**Comment by domi4484** [comment]
At least the control buttons should be visible... In the logs also there is no errors or strange outputs?

**Comment by domi4484** [comment]
Probably your QGIS is based on a too old Qt version. It need at lest Qt 5.15. You can find qgis compiled with this Qt in the new OSGeo installer, the one marked with "testing (upcoming replacement with newer dependencies...":
[https://qgis.org/fr/site/forusers/download.html](https://qgis.org/fr/site/forusers/download.html)

**Comment by ponceta** [comment]
Installed QGIS 3.20 with new osgeo4w installer.

Had some issue installing it with commandline parameters
https://github.com/qgis/QGIS/issues/44157

Works as described in documentation.

![image](https://user-images.githubusercontent.com/8614223/125627578-0da0f9fa-08b4-4b35-99b3-49842a2a9a58.png)

**Comment by domi4484** [comment]
@ponceta ok good :)
although i see there is still a problem with some icons under windows... the .mp4 file in documents should have an icon for the file type
