### ISSUE TITLE
Document layer not editable

### ISSUE THREAD

**Issue by ponceta** [opengisch/qgis-document-management-system-plugin#8]
Buttons are not available when the document layer is not in edit mode. This can be not very "ergonomic" when using it on a daily basis.

![image](https://user-images.githubusercontent.com/8614223/125628034-bb552b7c-d41e-4e1c-a68f-805cd160160f.png)

**Comment by domi4484** [comment]
You would hide them completely or maybe just disable them?

**Comment by ponceta** [comment]
Disable buttons preferably.

IMHO we miss here
- [ ] Edition start and stop
- [ ] Save
- [ ] Drop file

Or there's something on the usability/ergonomy I'm missing.
