### ISSUE TITLE
Add document create a None entry not editable

### ISSUE THREAD

**Issue by ponceta** [opengisch/qgis-document-management-system-plugin#9]
![image](https://user-images.githubusercontent.com/8614223/125628839-1df2de1c-bf67-48f7-abf0-17c91acd4d71.png)

Seems a bit weird, a demo would be welcome to test it the way it's meant to be used.

Show form option is available for existing documents.

![image](https://user-images.githubusercontent.com/8614223/125629202-d3fa0519-c24d-4c48-bee4-ef834adef338.png)

**Comment by domi4484** [comment]
I don't know where this None entry comes from... Ill try to reproduce it.
If you want to setup a call for a quick demo let me now!

**Comment by domi4484** [comment]
This can be reproduced by linking a document and afterwards trying to add one. It seems to be a bug in QGIS, when linking a feature internally the widget property "force-suppress-popup" is set to true and not reset after linking.
The solution is not clear at the moment.
